src/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('book_list/', views.BookList.as_view(), name="book-list"),
    path('book/<int:pk>/', views.BookDetail.as_view(), name="book-view"),
    path('book_add/', views.BookAdd.as_view(), name="book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name="book-edit"),
    path('book_search/', views.BookSearch.as_view(), name="book-search"),
]

src/handbook/urls.py
from django.urls import path
from . import views

app_name = "hb"

urlpatterns = [
    path('author_list/', views.AuthorList.as_view(), name="author-list"),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name="author-view"),
    path('author_add/', views.AuthorAdd.as_view(), name="author-add"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name="author-edit"),
    path('serie_list/', views.SerieList.as_view(), name="serie-list"),
    path('serie/<int:pk>/', views.SerieDetail.as_view(), name="serie-view"),
    path('serie_add/', views.SerieAdd.as_view(), name="serie-add"),
    path('serie_delete/<int:pk>/', views.SerieDelete.as_view(), name="serie-delete"),
    path('serie_edit/<int:pk>/', views.SerieEdit.as_view(), name="serie-edit"),
    path('genre_list/', views.GenreList.as_view(), name="genre-list"),
    path('genre/<int:pk>/', views.GenreDetail.as_view(), name="genre-view"),
    path('genre_add/', views.GenreAdd.as_view(), name="genre-add"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name="genre-edit"),
    path('publisher_list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name="publisher-view"),
    path('publisher_add/', views.PublisherAdd.as_view(), name="publisher-add"),
    path('publisher_delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
    path('publisher_edit/<int:pk>/', views.PublisherEdit.as_view(), name="publisher-edit"),
]

src/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('cart/', views.AddToCart.as_view(), name="add-to-cart"),
    path('delete_from_cart/<int:pk>/', views.DeleteFromCart.as_view(), name="delete-from-cart"),
    path('update_cart/', views.UpdateCart.as_view(), name="update-cart"),
    path('order_list/', views.OrderList.as_view(), name="order-list"),
    path('order_view/<int:pk>/', views.OrderView.as_view(), name="order-view"),
    path('order_edit/<int:pk>/', views.OrderEdit.as_view(), name="order-edit"),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name="order-delete"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from book import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view()),
    path('hb/', include('handbook.urls', namespace='hb')),
    path('book/', include('book.urls', namespace='book')),
    path('auth/', include('user_app.urls', namespace='user_app')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_app/urls.py
from django.urls import path
from . import views

app_name = "user_app"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#712cf9">
        <link href="{% static '/bs/css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static '/bs/js/bootstrap.bundle.min.js' %}"></script>
        <link href="{% static '/bs/css/sticky-footer-navbar.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
        {% include 'style.html' %}
    </head>
    <style>
        body {
            background: #000 url("{% static 'font.png' %}");
            background-attachment: fixed;
            background-repeat: repeat-y repeat-y; /* Изображение повторяется по горизонтали */
           
        }
    </style>
    <body class="d-flex flex-column h-100">
        {% include 'nav-bar.html' %}
        <main class="flex-shrink-0">
            <div class="container">
                <h1>{% block header %}{% endblock header %}</h1>
                {% block body %}{% endblock body %}
            </div>
        </main>
        <script src="" async defer></script>
    </body>
</html>

src/templates/carousel.html
{% load static %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static '/carousel_3.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '/carousel_2.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '/carousel_1.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

src/templates/dropdown.html
<ul class="navbar-nav">
  <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
  <ul class="dropdown-menu dropdown-menu-dark">
    {% if user.is_authenticated %}
    <li><a class="dropdown-item disabled">{{ user }}</a></li>
    <li><a class="dropdown-item" href="{% url 'user_app:logout' %}">Sign out</a></li>
    {% else %}
    <li><a class="dropdown-item" href="{% url 'user_app:login' %}">Sign in</a></li>
    {% endif %}
    <li><a class="dropdown-item" href="{% url 'orders:add-to-cart' %}"><i class="bi bi-cart"></i>Cart</a></li>
  </ul>
</ul>

src/templates/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>{% block title %}{% endblock title %}</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="theme-color" content="#712cf9">
      <link href="{% static '/bs/css/bootstrap.min.css' %}" rel="stylesheet">
      <script src="{% static '/bs/js/bootstrap.bundle.min.js' %}"></script>
      <link href="{% static '/bs/css/sticky-footer-navbar.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
      {% include 'style.html' %}
      <link href="{% static '/bs/css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <main class="form-signin w-100 m-auto">
      <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">Bookoholik</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>                
            </div>
          </div>
        </nav>
      </header>
      <div class="container">
        <h1>{% block header %}{% endblock header %}</h1>
        {% block body %}{% endblock body %}
      </div>
    </main>
    <script src="" async defer></script>
  </body>
</html>

src/templates/nav-bar.html
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Bookoholik</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'book:book-list' %}">Book's catalogue</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:author-list' %}">Author List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:serie-list' %}">Serie List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:genre-list' %}">Genre List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:publisher-list' %}">Publisher List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'orders:order-list' %}">Order List</a>
            </li>
            {% endif %}
            {% for group in user.groups.all %}
            {%  if 'Managers' == group.name %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:author-list' %}">Author List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:serie-list' %}">Serie List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:genre-list' %}">Genre List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hb:publisher-list' %}">Publisher List</a>
            </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:order-list' %}">Order List</a>
          </li>
          {% endif %}
          {% endfor %}
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          </ul>
          <a href="{% url 'book:book-search' %}"><button class="btn btn-outline-success" type="submit">Search</button></a>
          {% include 'dropdown.html' %}
        </div>
    </div>
  </nav>
</header>

src/templates/pagination.html
{% if is_paginated %}
  <div class="row">
    <div class="col-sm-4">
      <div class="dataTables_info" id="dynamic-table_info" role="status" aria-live="polite">
          Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} results
      </div>
    </div>
    <div class="col-sm-4>
      <div class="dataTables_paginate paging_simple_numbers" id="dynamic-table_paginate">
        <ul class="pagination">
        <div>
          <span>
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            <span>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
            </span>
        </div>
    </div>
  </div>
{% endif %}

src/templates/style.html
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
    .pic {
      text-align: center;
      }
  </style>