src/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('book_list/', views.BookList.as_view(), name="book-list"),
    path('book/<int:pk>/', views.BookDetail.as_view(), name="book-view"),
    path('book_add/', views.BookAdd.as_view(), name="book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name="book-edit"),
    path('book_search/', views.BookSearch.as_view(), name="book-search"),
]

src/handbook/urls.py
from django.urls import path
from . import views

app_name = "hb"

urlpatterns = [
    path('author_list/', views.AuthorList.as_view(), name="author-list"),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name="author-view"),
    path('author_add/', views.AuthorAdd.as_view(), name="author-add"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name="author-edit"),
    path('serie_list/', views.SerieList.as_view(), name="serie-list"),
    path('serie/<int:pk>/', views.SerieDetail.as_view(), name="serie-view"),
    path('serie_add/', views.SerieAdd.as_view(), name="serie-add"),
    path('serie_delete/<int:pk>/', views.SerieDelete.as_view(), name="serie-delete"),
    path('serie_edit/<int:pk>/', views.SerieEdit.as_view(), name="serie-edit"),
    path('genre_list/', views.GenreList.as_view(), name="genre-list"),
    path('genre/<int:pk>/', views.GenreDetail.as_view(), name="genre-view"),
    path('genre_add/', views.GenreAdd.as_view(), name="genre-add"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name="genre-edit"),
    path('publisher_list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name="publisher-view"),
    path('publisher_add/', views.PublisherAdd.as_view(), name="publisher-add"),
    path('publisher_delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
    path('publisher_edit/<int:pk>/', views.PublisherEdit.as_view(), name="publisher-edit"),
]

src/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('cart/', views.AddToCart.as_view(), name="add-to-cart"),
    path('delete_from_cart/<int:pk>/', views.DeleteFromCart.as_view(), name="delete-from-cart"),
    path('update_cart/', views.UpdateCart.as_view(), name="update-cart"),
    path('order_list/', views.OrderList.as_view(), name="order-list"),
    path('order_view/<int:pk>/', views.OrderView.as_view(), name="order-view"),
    path('order_edit/<int:pk>/', views.OrderEdit.as_view(), name="order-edit"),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name="order-delete"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from book import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view()),
    path('hb/', include('handbook.urls', namespace='hb')),
    path('book/', include('book.urls', namespace='book')),
    path('auth/', include('user_app.urls', namespace='user_app')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/book/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

class Book(models.Model):
    name = models.CharField(
        verbose_name="Book's name",
        max_length=50,
    )
    photo = models.ImageField(
        upload_to='images/',
        verbose_name="Photo",
        height_field=None,
        width_field=None,
        max_length=100
        
    )
    price = models.DecimalField(
        verbose_name="Price",
        decimal_places=2,
        max_digits=7,
        blank=True,
        null=True
    )
    author  = models.ManyToManyField(
        'handbook.Author',
        verbose_name="Author",
        related_name="author"
    )
    series = models.ForeignKey(
        'handbook.Serie',
        on_delete=models.PROTECT,
        verbose_name="Serie",
        related_name="serie",
        blank=True,
        null=True
    )
    genre = models.ManyToManyField(
        'handbook.Genre',
        verbose_name="Genre",
        related_name="genre"
    )
    year = models.DateField(
        verbose_name="Year of publishing",
        blank=True,
        null=True
    )
    pages = models.IntegerField(
        verbose_name="Number of pages",
        blank=True,
        null=True
    )
    blinding = models.CharField(
        verbose_name="Flinding's name",
        max_length=50,
        blank=True,
        null=True
    )
    format = models.CharField(
        verbose_name="Format's name",
        max_length=50,
        blank=True,
        null=True
    )
    isbn = models.CharField(
        verbose_name="ISBN number",
        max_length=50,
        blank=True,
        null=True
    )
    weight = models.IntegerField(
        verbose_name="Weight gr.",
        blank=True,
        null=True
    )
    age_restrictions = models.IntegerField(
        verbose_name="age restrictions",
        blank=True,
        null=True
    )
    publisher = models.ForeignKey(
        'handbook.Publisher',
        on_delete=models.PROTECT,
        verbose_name="Publisher",
        related_name="publisher"
    )
    quantity_in_stock = models.IntegerField(
        verbose_name="Quantity in stock",
        blank=True,
        null=True
    )
    active = models.BooleanField(
        verbose_name="Active for order",
        blank=True,
        null=True
    )
    ratings = GenericRelation(
        Rating,
        related_query_name='books'
    )
    date_of_entry = models.DateField(
        verbose_name="Date of entry",
        auto_now_add=True,
        editable=False,
        blank=True,
        null=True
    )
    date_of_modified = models.DateField(
        verbose_name="Date of modified",
        auto_now=True,
        editable=True,
        blank=True,
        null=True
    )
    description = models.TextField(
        verbose_name="Book description",
        blank=True,
        null=True        
    )
    def __str__(self) -> str:
        return self.name

src/book/forms.py
from django.forms import ModelForm
from book import models

class BookAddForm(ModelForm):
    class Meta:
        model = models.Book
        fields = "__all__"

src/book/views.py
from django.urls import reverse_lazy
from django.views import generic
from . import models, forms

from django.contrib.auth.mixins import PermissionRequiredMixin

class HomePage(generic.TemplateView):
    template_name = "book/home.html"
    
    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['book_list'] = models.Book.objects.filter(ratings__isnull=False).order_by('ratings__average')[:10:-1]
        return context

class BookList(generic.ListView):
    template_name = "book/book_list.html"
    model = models.Book
    paginate_by = 20

class BookDetail(generic.DetailView):
    template_name = "book/book_view.html"
    model = models.Book
    
class BookAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "book/book_add.html"
    model = models.Book
    form_class = forms.BookAddForm
    permission_required = ('book.add_book')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("book:book-view", kwargs={'pk' : self.object.pk})

class BookDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "book/book_delete.html"
    model = models.Book
    success_url = reverse_lazy("book:book-list")
    permission_required = ('book.delete_book')
    login_url = "user_app:login"

class BookEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "book/book_edit.html"
    model = models.Book
    form_class = forms.BookAddForm
    permission_required = ('book.change_book')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("book:book-view", kwargs={'pk' : self.object.pk})

class BookSearch(generic.ListView):
    template_name = "book/book_search.html"
    model = models.Book

    def get_queryset(self, *args, **kwargs):
        q = self.request.GET.get('search_query')
        if q:
            qs = self.model.objects.filter(name__contains=q)
        else:
            qs = []
        return qs
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('search_query', '')
        context['search_query'] = q
        return context

src/book/templates/book/book_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book add{% endblock title %}   
{% block header %}Add a book{% endblock header %}
{% block body %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/book/templates/book/book_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete book: {{ object }} {% endblock title %}   
{% block header %}Are you sure? You are about to delete: {{ object }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/book/templates/book/book_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book edit: {{ object }} {% endblock title %}   
{% block header %}Edit book: {{ object }}{% endblock header %}
{% block body %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/book/templates/book/book_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book list{% endblock title %}   
{% block header %}Book list{% endblock header %}
{% block body %}
    <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Photo</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            {% if user.is_superuser %}
                <th scope="col">Actions</th>
            {% endif %}
            {% for group in user.groups.all %}
            {%  if 'Managers' == group.name %}   
                <th scope="col">Actions</th>
            {% endif %}
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for row in object_list %}
        <tr>
        <td>{{ row.pk }}</td>
        <td>{% if row.photo %}
        <a href="{% url 'book:book-view' row.pk %}"><img src="{{ row.photo.url }}" height="80" width="45" alt="..."></a>
        {% else %}
        <a href="{% url 'book:book-view' row.pk %}"><img src="{% static '/no-image.jpg' %}"  height="80" width="45" alt="..."></a>
        {% endif %}</td>
        <td><a href="{% url 'book:book-view' row.pk %}"> {{ row.name }}</td>
        <td>{{ row.price }} $</td>
        {% if user.is_superuser %}
        <td><a href="{% url 'book:book-edit' row.pk %}"><i class="bi bi-pencil-square"></i>Edit<a href="{% url 'book:book-delete' row.pk %}"><i class="bi bi-trash3"></i>Delete</td>
        {% endif %}
        {% for group in user.groups.all %}
        {%  if 'Managers' == group.name %}
        <td><a href="{% url 'book:book-edit' row.pk %}"><i class="bi bi-pencil-square"></i>Edit<a href="{% url 'book:book-delete' row.pk %}"><i class="bi bi-trash3"></i>Delete</td>
        {% endif %}
        {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% include "pagination.html" %}
{% if user.is_superuser %}
<br><a href="{% url 'book:book-add' %}"> <button type="button" class="btn btn-primary">Add book</button>
{% endif %}
{% for group in user.groups.all %}
{%  if 'Managers' == group.name %}
<br><a href="{% url 'book:book-add' %}"> <button type="button" class="btn btn-primary">Add book</button>
{% endif %}
{% endfor %}
{% endblock body %}

src/book/templates/book/book_search.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book search{% endblock title %}   
{% block header %}Book search{% endblock header %}
{% block body %}
<form action="{% url 'book:book-search' %}" class="d-flex" role="search" method="get">
    <input class="form-control me-2" type="search" name="search_query" placeholder="Search" aria-label="Search" value="{{search_query}}">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<h2>Results:</h2>
{% for book in object_list %}
<a href="{% url 'book:book-view' book.pk %}">{{ book.name }} <br>
{% endfor %}
{% endblock body %}

src/book/templates/book/book_view.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% load crispy_forms_tags %}
{% block title %}Book: {{ object }} {% endblock title %}   
{% block header %}{{ object }}{% endblock header %}
{% block body %} 
  <div class="card mb-12">
    <div class="row g-0">
      <div class="col-md-4">
        {% if object.photo %}
        <img src="{{ object.photo.url }}" width="100" height="600" class="card-img-top" alt="...">
        {% else %}
        <img src="{% static '/no-image.jpg' %}" class="card-img-top" alt="...">
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{object.name}}</h5>
          <p class="card-text">{{object.description}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Author: {% for author in object.author.all %}<a href="{% url 'hb:author-view' author.pk %}">{{author.name}}</a>{%endfor%}</li>
          <li class="list-group-item">Serie: {{ object.serie }}</li>
          <li class="list-group-item">Genre: {% for genre in object.genre.all %}<a href="{% url 'hb:genre-view' genre.pk %}">{{genre.name}}</a>{%endfor%}</li>
          <li class="list-group-item">Publisher: <a href="{% url 'hb:publisher-view' object.publisher.pk %}">{{ object.publisher }}</a></li>
          <li class="list-group-item">Quantity in stock: {{ object.quantity_in_stock }}</li>
          <li class="list-group-item">Price: {{ object.price }} $</li>
          <li class="list-group-item">{% ratings object %}</li>     
        </ul>
        <form action="{% url 'orders:add-to-cart' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ object.pk }}">
            <div class="card-body row">
              <div class="col-sm-2">
                <input type="submit" class="btn btn-primary"value="Add to cart" id="add_to_cart">
              </div>
              <div class="col-sm-2">
                <input type="number" class="form-control" name="quantity" min="1" max="{{object.quantity_in_stock}}" step="1" value="1">
              </div>
            </div>
          </div>   
        </form>
      </div>
    </div>
{% endblock body %}  

src/book/templates/book/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home Page{% endblock title %}
{% block header %}{% endblock header %}   
{% block body %}
{% include 'carousel.html' %}
<br>
<div class="row row-cols-1 row-cols-md-5 g-4">
{% for book in book_list %}
  <div class="col">
    <div class="card" style="width: 14rem; height:30rem">
    {% if book.photo %}
    <br>
    <p class="pic"><a href="{% url 'book:book-view' book.pk %}"><img class="bd-placeholder-img rounded-circle" width="150" height="150" src="{{ book.photo.url }}"></a></p>
    {% else %}
    <br>
    <p class="pic"><a href="{% url 'book:book-view' book.pk %}"><img class="bd-placeholder-img rounded-circle" width="150" height="150" src="{% static '/no-image.jpg' %}"></a></p>
     {% endif %}
      <div class="card-body">
      <h5 class="card-title"><a href="{% url 'book:book-view' book.pk %}">{{book.name}}</a></h5>
      <p class="card-text">Author: {% for author in book.author.all %}{{author.name}}{%endfor%}</p>
      <p class="card-text">Genre: {% for genre in book.genre.all %}{{genre.name}}{%endfor%}</p>
      <p class="card-text">Price: {{ book.price }}$</p>
      </div>
    <a href="{% url 'book:book-view' book.pk %}#add_to_cart" class="btn btn-primary">Buy now</a>
    </div>
  </div>
{% endfor %}
</div>
<p class="mt-5 mb-3 text-muted">&copy; 2022</p>
{% endblock body %}   