src/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('book_list/', views.BookList.as_view(), name="book-list"),
    path('book/<int:pk>/', views.BookDetail.as_view(), name="book-view"),
    path('book_add/', views.BookAdd.as_view(), name="book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name="book-edit"),
    path('book_search/', views.BookSearch.as_view(), name="book-search"),
]

src/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('cart/', views.AddToCart.as_view(), name="add-to-cart"),
    path('delete_from_cart/<int:pk>/', views.DeleteFromCart.as_view(), name="delete-from-cart"),
    path('update_cart/', views.UpdateCart.as_view(), name="update-cart"),
    path('order_list/', views.OrderList.as_view(), name="order-list"),
    path('order_view/<int:pk>/', views.OrderView.as_view(), name="order-view"),
    path('order_edit/<int:pk>/', views.OrderEdit.as_view(), name="order-edit"),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name="order-delete"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from book import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view()),
    path('hb/', include('handbook.urls', namespace='hb')),
    path('book/', include('book.urls', namespace='book')),
    path('auth/', include('user_app.urls', namespace='user_app')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from book import models as book_models

user = get_user_model()

class Cart(models.Model):
    customer = models.ForeignKey(
        user,
        on_delete=models.PROTECT,
        related_name="carts",
        verbose_name="Customer",
        null=True,
        blank=True
    )
    created_date=models.DateTimeField(
        verbose_name="Created",
        auto_now_add=True,
        editable=False
    )
    updated_date=models.DateTimeField(
        verbose_name="Updated",
        auto_now=True,
        editable=True
    )

    def total_price(self):
        total = 0
        for good in self.goods.all():
            total += good.price
        return total

class BookInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.PROTECT,
        related_name="goods",
        verbose_name="Book in a Cart",
    )
    book = models.ForeignKey(
        book_models.Book,
        on_delete=models.PROTECT,
        related_name="goods",
        verbose_name="Book",
    )
    quantity = models.SmallIntegerField(
        verbose_name="Quantity"
    )
    price = models.DecimalField(
        verbose_name="Price",
        decimal_places=2,
        max_digits=7,
        null=True,
        blank=True
    )
    created_date=models.DateTimeField(
        verbose_name="Created",
        auto_now_add=True,
        editable=False
    )
    updated_date=models.DateTimeField(
        verbose_name="Updated",
        auto_now=True,
        editable=True
    )

class Status(models.Model):
    name = models.TextField(
        max_length=50,
        verbose_name="Name",
    )

    def __str__(self) -> str:
        return self.name

class Order(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.PROTECT,
        related_name="orders",
        verbose_name="Cart"           
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name="orders",
        verbose_name="Status",
    )
        
    name = models.TextField(
        max_length=50,
        verbose_name="Name",
        blank=True,
        null=True
    )
    email = models.EmailField(
        verbose_name="E-mail",
        max_length=50,
        blank=True,
        null=True
    )
    phone = models.TextField(
        max_length=50,
        verbose_name="Phone",
        blank=True,
        null=True
    )
    address = models.TextField(
        max_length=50,
        verbose_name="Address",
        blank=True,
        null=True
    )
    comment = models.TextField(
        max_length=50,
        verbose_name="Comment",
        blank=True,
        null=True
    )
    created_date=models.DateTimeField(
        verbose_name="Created",
        auto_now_add=True,
        editable=False
    )
    updated_date=models.DateTimeField(
        verbose_name="Updated",
        auto_now=True,
        editable=True
    )    

src/orders/forms.py
from django.forms import ModelForm
from orders import models

class CartAddForm(ModelForm):
    class Meta:
        model = models.Cart
        fields = "__all__"

class BookInCartAddForm(ModelForm):
    class Meta:
        model = models.BookInCart
        fields = "__all__"

class OrderAddForm(ModelForm):
    class Meta:
        model = models.Order
        fields = "__all__"

src/orders/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from . forms import BookInCartAddForm, CartAddForm, OrderAddForm
from . models import BookInCart, Cart, Order, Status
from book.models import Book
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.

def get_cart(view):
    card_id = view.request.session.get('cart')
    if not card_id:
        if view.request.user.is_anonymous:
            customer = None
        else:
            customer = view.request.user
        cart = Cart.objects.create(
            customer=customer
        )
        view.request.session['cart'] = cart.pk
    else:
        cart = Cart.objects.get(pk=card_id)
    return cart

class DeleteFromCart(generic.DeleteView):
    template_name = "orders/delete-item.html"
    model = BookInCart
    success_url = reverse_lazy("orders:add-to-cart")

class UpdateCart(generic.UpdateView):
    template_name = "orders/cart.html"
    model = BookInCart
    form_class = BookInCartAddForm
    success_url = reverse_lazy("orders:add-to-cart")
        
    def get_object(self, **kwargs):
        cart = get_cart(self)
        for good in self.request.POST.keys():
            if good[:5] == "good_":
                good_in_cart_pk = good.split("_")[1]
                book_in_cart = BookInCart.objects.get(pk=int(good_in_cart_pk))
                book_in_cart.quantity = int(self.request.POST.get(good))
                book_in_cart.price = book_in_cart.book.price * book_in_cart.quantity
                book_in_cart.save()
        action_type = self.request.POST.get('action_type')
        if action_type == 'Order':
            order = Order.objects.create(
            cart = book_in_cart.cart,
            status = Status(pk=1),
            name = self.request.POST.get('name'),
            email = self.request.POST.get('email'),
            phone = self.request.POST.get('phone'),
            address = self.request.POST.get('address'),
            comment = self.request.POST.get('comment')
            )
            del self.request.session["cart"]
        return cart
    
    def render_to_response(self, context, **response_kwargs):
        action_type = self.request.POST.get('action_type')
        if action_type == 'Order':
            return HttpResponseRedirect("/")
        return super().render_to_response(context, **response_kwargs)

 
class AddToCart(generic.UpdateView):
    model = Cart
    form_class = CartAddForm
    template_name = "orders/cart.html"
    success_url = reverse_lazy("orders:add-to-cart")
    def get_object(self, **kwargs):
        book_id = self.request.POST.get('book_id')
        cart = get_cart(self)
        if book_id:
            quantity = int(self.request.POST.get('quantity'))
            book =  Book.objects.get(pk=book_id)
            price = book.price * quantity
            book_in_cart, created = BookInCart.objects.get_or_create(
                cart=cart,
                book=book,
                defaults={
                    'quantity': quantity,
                    'price': price
                }
            )
            if not created:
                book_in_cart.quantity = book_in_cart.quantity + quantity
                book_in_cart.price = book_in_cart.price + price
                book_in_cart.save()
        return cart

class OrderList(PermissionRequiredMixin, generic.ListView):
    template_name = "orders/order_list.html"
    model = Order
    paginate_by = 20
    permission_required = ('orders.view_order')
    login_url = "user_app:login"
    
class OrderView(PermissionRequiredMixin, generic.DetailView):
    template_name = "orders/order_view.html"
    model = Order
    permission_required = ('orders.view_order')
    login_url = "user_app:login"

class OrderEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "orders/order_edit.html"
    model = Order
    form_class = OrderAddForm
    permission_required = ('orders.change_order')
    login_url = "user_app:login"
    success_url = reverse_lazy("orders:order-list")

class OrderDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "orders/order_delete.html"
    model = Order
    success_url = reverse_lazy("orders:order-list")
    permission_required = ('orders.delete_order')
    login_url = "user_app:login"
    

 

src/orders/templates/orders/cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block header %}Cart{% endblock header %}   
{% block body %}
<form action="{% url 'orders:update-cart' %}" method="post">
{% csrf_token %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <td>Name</td>
                <td>Quantity</td>
                <td>Price</td>
                <td>Actions</td>
            </tr>
        </thead>    
        <tbody>
        {% for item in cart.goods.all %}
            <tr>
                <td>{{ item.book.name }}</td>
                <td><input type="number" name="good_{{item.pk}}" id="" value="{{ item.quantity }}" min="0" step="1"></td>
                <td>{{ item.price }}</td>
                <td><a href="{% url 'orders:delete-from-cart' item.pk %}"><i class="bi bi-trash3">Delete</i></td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="1">Total price</td>
                <td><input type="submit" name="action_type" value="Update" class="btn btn-success" ></td>
                <td>{{ cart.total_price }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
<br>
<h4>Please fill in the delivery details:</h4><br>
<input type="text" class="form-control me-2" placeholder="Name" name="name" id=""><br>
<input type="email" class="form-control me-2" placeholder="E-mail" name="email" id=""><br>
<input type="tel" class="form-control me-2" placeholder="Phone number" name="phone" id=""><br>
<input type="text" class="form-control me-2" placeholder="Address" name="address" id=""><br>
<input type="text" class="form-control me-2" placeholder="Comment" name="comment" id=""><br>
<input type="submit" name="action_type" value="Order" class="btn btn-warning">
</form>
{% endblock body %}   

src/orders/templates/orders/delete-item.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block header %}{% endblock header %}   
{% block body %}
    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Are you sure?">
    </form>
{% endblock body %}   

src/orders/templates/orders/order_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete order: {{ object }} {% endblock title %}   
{% block header %}Are you sure? You are about to delete order: {{ object }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/orders/templates/orders/order_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Order edit: {{ object }} {% endblock title %}   
{% block header %}Order book: {{ object }}{% endblock header %}
{% block body %} 
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/orders/templates/orders/order_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Order list {% endblock title %}   
{% block header %}Order list{% endblock header %}
{% block body %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Cart</th>
                <th scope="col">Client Name</th>
                <th scope="col">Order status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for row in object_list %}
            <tr>
                <td><a href="{% url 'orders:order-view' row.pk %}">{{ row.pk }}</td>
                <td><a href="{% url 'orders:order-view' row.pk %}">{{ row.cart }}</td>
                <td><a href="{% url 'orders:order-view' row.pk %}">{{ row.name }}</td>
                <td><a href="{% url 'orders:order-view' row.pk %}">{{ row.status }}</td>            
                <td><a href="{% url 'orders:order-edit' row.pk %}"><i class="bi bi-pencil-square"></i>Edit<a href="{% url 'orders:order-delete' row.pk %}"><i class="bi bi-trash3"></i>Delete</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% include "pagination.html" %}
{% endblock body %}

src/orders/templates/orders/order_view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Order: {{ object }} {% endblock title %}   
{% block header %}{{ object }}{% endblock header %}
{% block body %} 
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Name: {{ object.name }}</li>
    <li class="list-group-item">Cart: {{ object.cart }}</li>
    <li class="list-group-item">Books: <br> {% for book in object.cart.goods.all %}{{book.book.name}} {{book.quantity}} pc. <br>{%endfor%}</li>
    <li class="list-group-item">Status: {{ object.status }}</li>
    <li class="list-group-item">Email: {{ object.email }}</li>
    <li class="list-group-item">Phone: {{ object.phone }}</li>
    <li class="list-group-item">Address: {{ object.address }}</li>
    <li class="list-group-item">Comment: {{ object.comment }} $</li>
  </ul>
{% endblock body %}  