src/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('book_list/', views.BookList.as_view(), name="book-list"),
    path('book/<int:pk>/', views.BookDetail.as_view(), name="book-view"),
    path('book_add/', views.BookAdd.as_view(), name="book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name="book-edit"),
    path('book_search/', views.BookSearch.as_view(), name="book-search"),
]

src/handbook/urls.py
from django.urls import path
from . import views

app_name = "hb"

urlpatterns = [
    path('author_list/', views.AuthorList.as_view(), name="author-list"),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name="author-view"),
    path('author_add/', views.AuthorAdd.as_view(), name="author-add"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name="author-edit"),
    path('serie_list/', views.SerieList.as_view(), name="serie-list"),
    path('serie/<int:pk>/', views.SerieDetail.as_view(), name="serie-view"),
    path('serie_add/', views.SerieAdd.as_view(), name="serie-add"),
    path('serie_delete/<int:pk>/', views.SerieDelete.as_view(), name="serie-delete"),
    path('serie_edit/<int:pk>/', views.SerieEdit.as_view(), name="serie-edit"),
    path('genre_list/', views.GenreList.as_view(), name="genre-list"),
    path('genre/<int:pk>/', views.GenreDetail.as_view(), name="genre-view"),
    path('genre_add/', views.GenreAdd.as_view(), name="genre-add"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name="genre-edit"),
    path('publisher_list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name="publisher-view"),
    path('publisher_add/', views.PublisherAdd.as_view(), name="publisher-add"),
    path('publisher_delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
    path('publisher_edit/<int:pk>/', views.PublisherEdit.as_view(), name="publisher-edit"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from book import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view()),
    path('hb/', include('handbook.urls', namespace='hb')),
    path('book/', include('book.urls', namespace='book')),
    path('auth/', include('user_app.urls', namespace='user_app')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/book/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

class Book(models.Model):
    name = models.CharField(
        verbose_name="Book's name",
        max_length=50,
    )
    photo = models.ImageField(
        upload_to='images/',
        verbose_name="Photo",
        height_field=None,
        width_field=None,
        max_length=100
        
    )
    price = models.DecimalField(
        verbose_name="Price",
        decimal_places=2,
        max_digits=7,
        blank=True,
        null=True
    )
    author  = models.ManyToManyField(
        'handbook.Author',
        verbose_name="Author",
        related_name="author"
    )
    series = models.ForeignKey(
        'handbook.Serie',
        on_delete=models.PROTECT,
        verbose_name="Serie",
        related_name="serie",
        blank=True,
        null=True
    )
    genre = models.ManyToManyField(
        'handbook.Genre',
        verbose_name="Genre",
        related_name="genre"
    )
    year = models.DateField(
        verbose_name="Year of publishing",
        blank=True,
        null=True
    )
    pages = models.IntegerField(
        verbose_name="Number of pages",
        blank=True,
        null=True
    )
    blinding = models.CharField(
        verbose_name="Flinding's name",
        max_length=50,
        blank=True,
        null=True
    )
    format = models.CharField(
        verbose_name="Format's name",
        max_length=50,
        blank=True,
        null=True
    )
    isbn = models.CharField(
        verbose_name="ISBN number",
        max_length=50,
        blank=True,
        null=True
    )
    weight = models.IntegerField(
        verbose_name="Weight gr.",
        blank=True,
        null=True
    )
    age_restrictions = models.IntegerField(
        verbose_name="age restrictions",
        blank=True,
        null=True
    )
    publisher = models.ForeignKey(
        'handbook.Publisher',
        on_delete=models.PROTECT,
        verbose_name="Publisher",
        related_name="publisher"
    )
    quantity_in_stock = models.IntegerField(
        verbose_name="Quantity in stock",
        blank=True,
        null=True
    )
    active = models.BooleanField(
        verbose_name="Active for order",
        blank=True,
        null=True
    )
    ratings = GenericRelation(
        Rating,
        related_query_name='books'
    )
    date_of_entry = models.DateField(
        verbose_name="Date of entry",
        auto_now_add=True,
        editable=False,
        blank=True,
        null=True
    )
    date_of_modified = models.DateField(
        verbose_name="Date of modified",
        auto_now=True,
        editable=True,
        blank=True,
        null=True
    )
    description = models.TextField(
        verbose_name="Book description",
        blank=True,
        null=True        
    )
    def __str__(self) -> str:
        return self.name

src/handbook/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(
        verbose_name="Author's name",
        max_length=50
    )
    description = models.TextField(
        verbose_name="Author's description",
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return self.name

class Serie(models.Model):
    name = models.CharField(
        verbose_name="Serie's name",
        max_length=50,
        unique=True
    )
    description = models.TextField(
        verbose_name="Serie's description",
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return self.name

class Genre(models.Model):
    name = models.CharField(
        verbose_name="Genre's name",
        max_length=50,
        unique=True
    )
    description = models.TextField(
        verbose_name="Genre's description",
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return self.name

class Publisher(models.Model):
    name = models.CharField(
        verbose_name="Publisher's name",
        max_length=50,
        unique=True
    )
    description = models.TextField(
        verbose_name="Publisher description",
        blank=True,
        null=True        
    )
    def __str__(self) -> str:
        return self.name

src/book/forms.py
from django.forms import ModelForm
from book import models

class BookAddForm(ModelForm):
    class Meta:
        model = models.Book
        fields = "__all__"

src/handbook/forms.py
from django.forms import ModelForm
from handbook import models

class AuthorAddForm(ModelForm):
    class Meta:
        model = models.Author
        fields = "__all__"

class SerieAddForm(ModelForm):
    class Meta:
        model = models.Serie
        fields = "__all__"

class GenreAddForm(ModelForm):
    class Meta:
        model = models.Genre
        fields = "__all__"

class PublisherAddForm(ModelForm):
    class Meta:
        model = models.Publisher
        fields = "__all__"

src/book/views.py
from django.urls import reverse_lazy
from django.views import generic
from . import models, forms

from django.contrib.auth.mixins import PermissionRequiredMixin

class HomePage(generic.TemplateView):
    template_name = "book/home.html"
    
    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['book_list'] = models.Book.objects.filter(ratings__isnull=False).order_by('ratings__average')[:10:-1]
        return context

class BookList(generic.ListView):
    template_name = "book/book_list.html"
    model = models.Book
    paginate_by = 20

class BookDetail(generic.DetailView):
    template_name = "book/book_view.html"
    model = models.Book
    
class BookAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "book/book_add.html"
    model = models.Book
    form_class = forms.BookAddForm
    permission_required = ('book.add_book')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("book:book-view", kwargs={'pk' : self.object.pk})

class BookDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "book/book_delete.html"
    model = models.Book
    success_url = reverse_lazy("book:book-list")
    permission_required = ('book.delete_book')
    login_url = "user_app:login"

class BookEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "book/book_edit.html"
    model = models.Book
    form_class = forms.BookAddForm
    permission_required = ('book.change_book')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("book:book-view", kwargs={'pk' : self.object.pk})

class BookSearch(generic.ListView):
    template_name = "book/book_search.html"
    model = models.Book

    def get_queryset(self, *args, **kwargs):
        q = self.request.GET.get('search_query')
        if q:
            qs = self.model.objects.filter(name__contains=q)
        else:
            qs = []
        return qs
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('search_query', '')
        context['search_query'] = q
        return context

src/handbook/views.py
from django.urls import reverse_lazy
from django.views import generic
from . import models, forms
from django.contrib.auth.mixins import PermissionRequiredMixin

class AuthorList(PermissionRequiredMixin, generic.ListView):
    template_name = "handbook/author_list.html"
    model = models.Author
    paginate_by = 20
    permission_required = ('handbook.view_author')
    login_url = "user_app:login"

class AuthorDetail(generic.DetailView):
    template_name = "handbook/author_view.html"
    model = models.Author

class AuthorAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "handbook/author_add.html"
    model = models.Author
    form_class = forms.AuthorAddForm
    permission_required = ('handbook.add_author')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:author-view", kwargs={'pk' : self.object.pk})

class AuthorDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "handbook/author_delete.html"
    model = models.Author
    success_url = reverse_lazy("hb:author-list")
    permission_required = ('handbook.delete_author')
    login_url = "user_app:login"

class AuthorEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "handbook/author_edit.html"
    model = models.Author
    form_class = forms.AuthorAddForm
    permission_required = ('handbook.change_author')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:author-view", kwargs={'pk' : self.object.pk})

class SerieList(PermissionRequiredMixin, generic.ListView):
    template_name = "handbook/serie_list.html"
    model = models.Serie
    paginate_by = 20
    permission_required = ('handbook.view_serie')
    login_url = "user_app:login"

class SerieDetail(generic.DetailView):
    template_name = "handbook/serie_view.html"
    model = models.Serie

class SerieAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "handbook/serie_add.html"
    model = models.Serie
    form_class = forms.SerieAddForm
    permission_required = ('handbook.add_serie')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:serie-view", kwargs={'pk' : self.object.pk})

class SerieDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "handbook/serie_delete.html"
    model = models.Serie
    success_url = reverse_lazy("hb:serie-list")
    permission_required = ('handbook.delete_serie')
    login_url = "user_app:login"
    
class SerieEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "handbook/serie_edit.html"
    model = models.Serie
    form_class = forms.SerieAddForm
    permission_required = ('handbook.change_serie')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:serie-view", kwargs={'pk' : self.object.pk})

class GenreList(PermissionRequiredMixin, generic.ListView):
    template_name = "handbook/genre_list.html"
    model = models.Genre
    paginate_by = 20
    permission_required = ('handbook.view_genre')
    login_url = "user_app:login"

class GenreDetail(generic.DetailView):
    template_name = "handbook/genre_view.html"
    model = models.Genre

class GenreAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "handbook/genre_add.html"
    model = models.Genre
    form_class = forms.GenreAddForm
    permission_required = ('handbook.add_genre')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:genre-view", kwargs={'pk' : self.object.pk})

class GenreDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "handbook/genre_delete.html"
    model = models.Genre
    success_url = reverse_lazy("hb:genre-list")
    permission_required = ('handbook.delete_genre')
    login_url = "user_app:login"
    
class GenreEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "handbook/genre_edit.html"
    model = models.Genre
    form_class = forms.GenreAddForm
    permission_required = ('handbook.change_genre')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:genre-view", kwargs={'pk' : self.object.pk})

class PublisherList(PermissionRequiredMixin, generic.ListView):
    template_name = "handbook/publisher_list.html"
    model = models.Publisher
    paginate_by = 20
    permission_required = ('handbook.view_publisher')
    login_url = "user_app:login"

class PublisherDetail(generic.DetailView):
    template_name = "handbook/publisher_view.html"
    model = models.Publisher

class PublisherAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "handbook/publisher_add.html"
    model = models.Publisher
    form_class = forms.PublisherAddForm
    permission_required = ('handbook.add_publisher')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:publisher-view", kwargs={'pk' : self.object.pk})

class PublisherDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "handbook/publisher_delete.html"
    model = models.Publisher
    success_url = reverse_lazy("hb:publisher-list")
    permission_required = ('handbook.delete_publisher')
    login_url = "user_app:login"
    
class PublisherEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "handbook/publisher_edit.html"
    model = models.Publisher
    form_class = forms.PublisherAddForm
    permission_required = ('handbook.change_publisher')
    login_url = "user_app:login"

    def get_success_url(self) -> str:
        return reverse_lazy("hb:publisher-view", kwargs={'pk' : self.object.pk})

src/handbook/templates/handbook/author_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Author add{% endblock title %}   
{% block header %}Add a author{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/author_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Author item: {{ object.name }} {% endblock title %}   
{% block header %}Are you sure? You are about to delete author: {{ object.name }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/book_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Item: {{ object }} {% endblock title %}   
{% block header %}{{ object }}{% endblock header %}
{% block body %} 
        <b>Photo:</b> {{ object.photo }}<br>
        <b>Price:</b> {{ object.price }}<br>
        <b>Author:</b> {% for author in object.author.all %}{{author.name}}{%endfor%}<br>
        <b>Serie:</b> {{ object.serie }}<br>
        <b>Genre: </b>{% for genre in object.genre.all %}{{genre.name}}{%endfor%}<br>
        <b>Year:</b> {{ object.year}}<br>
        <b>Pages:</b> {{ object.pages }}<br>
        <b>Blinding:</b> {{ object.blinding }}<br>
        <b>Format:</b> {{ object.format }}<br>
        <b>ISBN:</b> {{ object.isbn }}<br>
        <b>Weight:</b> {{ object.weight }}<br>
        <b>Age of restrictions:</b> {{ object.age_restrictions }}<br>
        <b>Publisher:</b> {{ object.publisher }}<br>
        <b>Quantity in stock:</b> {{ object.quantity_in_stock }}<br>
        <b>Active for order:</b> {{ object.active }}<br>
        <b>Rating:</b> {{ object.rating }}<br>
        <b>Date of entry:</b> {{ object.date_of_entry }}<br>
        <b>Date of last modified:</b> {{ object.date_of_modified }}<br>
        <b>Description:</b> {{ object.description }}<br>
{% endblock body %}  

src/handbook/templates/handbook/genre_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Genre add {% endblock title %}   
{% block header %}Add a Genre{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/genre_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Genre edit: {{ object.name }} {% endblock title %}   
{% block header %}Edit genre: {{ object.name }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/genre_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Genre's list{% endblock title %}   
{% block header %}Genre's list{% endblock header %}
{% block body %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for row in object_list %}
            <tr>
                <td>{{ row.pk }}</td>
                <td><a href="{% url 'hb:genre-view' row.pk %}">{{ row.name }}</td>
                <td><a href="{% url 'hb:genre-edit' row.pk %}"><i class="bi bi-pencil-square"></i>Edit<a href="{% url 'hb:genre-delete' row.pk %}"><i class="bi bi-trash3"></i>Delete</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% include "pagination.html" %}
<br><a href="{% url 'hb:genre-add' %}"> <button type="button" class="btn btn-primary">Add genre</button>
{% endblock body %}

src/handbook/templates/handbook/genre_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Genre: {{ object.name }} {% endblock title %}   
{% block header %}{{ object.name }}{% endblock header %}
{% block body %} 
        <b>Description:</b> {{ object.description }}<br>
        {% if object.genre.all %}
        <b>List of books:</b><br>{% for book in object.genre.all %} <a href="{% url 'book:book-view' book.pk %}">{{ book.name }}<br>{% endfor %}
        {% endif %}
{% endblock body %}  

src/handbook/templates/handbook/item_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Delete item: {{ object }} {% endblock title %}   
{% block header %}Are you sure? You are about to delete: {{ object }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/publisher_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Publisher add{% endblock title %}   
{% block header %}Add a publisher{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/publisher_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Publisher's list {% endblock title %}   
{% block header %}Publisher's list{% endblock header %}
{% block body %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for row in object_list %}
            <tr>
                <td>{{ row.pk }}</td>
                <td><a href="{% url 'hb:publisher-view' row.pk %}"> {{ row.name }}</td>
                <td><a href="{% url 'hb:publisher-edit' row.pk %}"> <i class="bi bi-pencil-square"></i>Edit<a href="{% url 'hb:publisher-delete' row.pk %}"><i class="bi bi-trash3"></i>Delete</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% include "pagination.html" %}
<br><a href="{% url 'hb:publisher-add' %}"> <button type="button" class="btn btn-primary">Add publisher</button>
{% endblock body %}

src/handbook/templates/handbook/publisher_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Publisher: {{ object.name }}{% endblock title %}   
{% block header %}{{ object.name }}{% endblock header %}
{% block body %} 
        <b>Description:</b> {{ object.description }}<br>
        {% if object.publisher.all %}
        <b>List of books:</b><br>{% for book in object.publisher.all %}<a href="{% url 'book:book-view' book.pk %}">{{ book.name }}<br>{% endfor %}
        {% endif %}
{% endblock body %}  

src/handbook/templates/handbook/serie_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Serie add{% endblock title %}   
{% block header %}Add a serie{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/serie_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Serie edit: {{ object.name }} {% endblock title %}   
{% block header %}Edit Serie: {{ object.name }}{% endblock header %}
{% block body %} 
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br><input type="submit" class="btn btn-primary">
{% endblock body %}  

src/handbook/templates/handbook/serie_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Serie: {{ object.name }} {% endblock title %}   
{% block header %}{{ object.name }}{% endblock header %}
{% block body %} 
        <b>Description:</b> {{ object.description }}<br>
        {% if object.serie.all %}
        <b>List of books:</b><br>{% for book in object.serie.all %}<a href="{% url 'book:book-view' book.pk %}">{{ book.name }}<br>{% endfor %}
        {% endif %}
{% endblock body %}  